package com.pedrohnf688.api.modelo.enums;

public enum EnumStatusProjeto {
	
	COLETANDO_REQUISITOS, ANALISANDO_VIABILIDADE, DESENVOLVENDO_METODOLOGIA, 
	DESENVOLVENDO, REALIZANDO_TESTES, CONCLUIDO;
}
